/*
 * Decompiled with CFR 0.152.
 */
package com.wurmonline.server.spells;

import com.wurmonline.server.spells.Bearpaw;
import com.wurmonline.server.spells.Blaze;
import com.wurmonline.server.spells.Bless;
import com.wurmonline.server.spells.BlessingDark;
import com.wurmonline.server.spells.Bloodthirst;
import com.wurmonline.server.spells.BreakAltar;
import com.wurmonline.server.spells.CharmAnimal;
import com.wurmonline.server.spells.CircleOfCunning;
import com.wurmonline.server.spells.Cleanse;
import com.wurmonline.server.spells.Continuum;
import com.wurmonline.server.spells.Corrosion;
import com.wurmonline.server.spells.Corrupt;
import com.wurmonline.server.spells.Courier;
import com.wurmonline.server.spells.CureLight;
import com.wurmonline.server.spells.CureMedium;
import com.wurmonline.server.spells.CureSerious;
import com.wurmonline.server.spells.DarkMessenger;
import com.wurmonline.server.spells.DeepTentacles;
import com.wurmonline.server.spells.DemiseAnimal;
import com.wurmonline.server.spells.DemiseHuman;
import com.wurmonline.server.spells.DemiseLegendary;
import com.wurmonline.server.spells.DemiseMonster;
import com.wurmonline.server.spells.Dirt;
import com.wurmonline.server.spells.Disease;
import com.wurmonline.server.spells.Disintegrate;
import com.wurmonline.server.spells.Dispel;
import com.wurmonline.server.spells.Dominate;
import com.wurmonline.server.spells.DrainHealth;
import com.wurmonline.server.spells.DrainStamina;
import com.wurmonline.server.spells.EssenceDrain;
import com.wurmonline.server.spells.Excel;
import com.wurmonline.server.spells.FireHeart;
import com.wurmonline.server.spells.FirePillar;
import com.wurmonline.server.spells.Fireball;
import com.wurmonline.server.spells.FlamingAura;
import com.wurmonline.server.spells.FocusedWill;
import com.wurmonline.server.spells.Forecast;
import com.wurmonline.server.spells.ForestGiant;
import com.wurmonline.server.spells.FranticCharge;
import com.wurmonline.server.spells.Frostbrand;
import com.wurmonline.server.spells.FungusTrap;
import com.wurmonline.server.spells.Genesis;
import com.wurmonline.server.spells.Glacial;
import com.wurmonline.server.spells.GoatShape;
import com.wurmonline.server.spells.Heal;
import com.wurmonline.server.spells.Hellstrength;
import com.wurmonline.server.spells.HolyCrop;
import com.wurmonline.server.spells.HumidDrizzle;
import com.wurmonline.server.spells.Hypothermia;
import com.wurmonline.server.spells.IcePillar;
import com.wurmonline.server.spells.Incinerate;
import com.wurmonline.server.spells.Inferno;
import com.wurmonline.server.spells.KarmaBolt;
import com.wurmonline.server.spells.KarmaMissile;
import com.wurmonline.server.spells.KarmaSlow;
import com.wurmonline.server.spells.LandOfTheDead;
import com.wurmonline.server.spells.LifeTransfer;
import com.wurmonline.server.spells.LightOfFo;
import com.wurmonline.server.spells.LightToken;
import com.wurmonline.server.spells.Lightning;
import com.wurmonline.server.spells.LocateArtifact;
import com.wurmonline.server.spells.LocatePlayer;
import com.wurmonline.server.spells.LurkerDark;
import com.wurmonline.server.spells.LurkerDeep;
import com.wurmonline.server.spells.LurkerWoods;
import com.wurmonline.server.spells.MassStamina;
import com.wurmonline.server.spells.Mend;
import com.wurmonline.server.spells.MindStealer;
import com.wurmonline.server.spells.MirroredSelf;
import com.wurmonline.server.spells.MoleSenses;
import com.wurmonline.server.spells.MorningFog;
import com.wurmonline.server.spells.Nimbleness;
import com.wurmonline.server.spells.Nolocate;
import com.wurmonline.server.spells.OakShell;
import com.wurmonline.server.spells.Opulence;
import com.wurmonline.server.spells.PainRain;
import com.wurmonline.server.spells.Phantasms;
import com.wurmonline.server.spells.ProtectionAcid;
import com.wurmonline.server.spells.ProtectionFire;
import com.wurmonline.server.spells.ProtectionFrost;
import com.wurmonline.server.spells.ProtectionPoison;
import com.wurmonline.server.spells.Purge;
import com.wurmonline.server.spells.Rebirth;
import com.wurmonline.server.spells.Refresh;
import com.wurmonline.server.spells.RevealCreatures;
import com.wurmonline.server.spells.RevealSettlements;
import com.wurmonline.server.spells.RiteDeath;
import com.wurmonline.server.spells.RiteSpring;
import com.wurmonline.server.spells.RitualSun;
import com.wurmonline.server.spells.RottingGut;
import com.wurmonline.server.spells.RottingTouch;
import com.wurmonline.server.spells.RustMonster;
import com.wurmonline.server.spells.ScornOfLibila;
import com.wurmonline.server.spells.ShardOfIce;
import com.wurmonline.server.spells.SharedPain;
import com.wurmonline.server.spells.SixthSense;
import com.wurmonline.server.spells.Smite;
import com.wurmonline.server.spells.Spell;
import com.wurmonline.server.spells.SproutTrees;
import com.wurmonline.server.spells.StoneSkin;
import com.wurmonline.server.spells.StrongWall;
import com.wurmonline.server.spells.Summon;
import com.wurmonline.server.spells.SummonSkeleton;
import com.wurmonline.server.spells.SummonSoul;
import com.wurmonline.server.spells.SummonWorg;
import com.wurmonline.server.spells.SummonWraith;
import com.wurmonline.server.spells.Sunder;
import com.wurmonline.server.spells.TangleWeave;
import com.wurmonline.server.spells.Tornado;
import com.wurmonline.server.spells.Toxin;
import com.wurmonline.server.spells.TrueHit;
import com.wurmonline.server.spells.Truestrike;
import com.wurmonline.server.spells.Venom;
import com.wurmonline.server.spells.Vessle;
import com.wurmonline.server.spells.WallOfFire;
import com.wurmonline.server.spells.WallOfIce;
import com.wurmonline.server.spells.WallOfStone;
import com.wurmonline.server.spells.Ward;
import com.wurmonline.server.spells.Weakness;
import com.wurmonline.server.spells.WebArmour;
import com.wurmonline.server.spells.WildGrowth;
import com.wurmonline.server.spells.WillowSpine;
import com.wurmonline.server.spells.WindOfAges;
import com.wurmonline.server.spells.WisdomVynora;
import com.wurmonline.server.spells.WormBrains;
import com.wurmonline.server.spells.WrathMagranon;
import com.wurmonline.server.spells.ZombieInfestation;
import com.wurmonline.shared.constants.AttitudeConstants;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Logger;

public final class Spells
implements AttitudeConstants {
    private static final Logger logger = Logger.getLogger(Spells.class.getName());
    private static final Map<Integer, Spell> spells = new HashMap<Integer, Spell>();
    private static final Map<Integer, Spell> creatureSpells = new HashMap<Integer, Spell>();
    private static final Map<Integer, Spell> itemSpells = new HashMap<Integer, Spell>();
    private static final Map<Integer, Spell> woundSpells = new HashMap<Integer, Spell>();
    private static final Map<Byte, Spell> enchantments = new HashMap<Byte, Spell>();
    private static final Map<Integer, Spell> tileSpells = new HashMap<Integer, Spell>();
    public static Spell SPELL_AURA_SHARED_PAIN = new SharedPain();
    public static Spell SPELL_BEARPAWS = new Bearpaw();
    public static Spell SPELL_BLAZE = new Blaze();
    public static Spell SPELL_BLESS = new Bless();
    public static Spell SPELL_BLESSINGS_OF_THE_DARK = new BlessingDark();
    public static Spell SPELL_BLOODTHIRST = new Bloodthirst();
    public static Spell SPELL_BREAK_ALTAR = new BreakAltar();
    public static Spell SPELL_CHARM_ANIMAL = new CharmAnimal();
    public static Spell SPELL_CIRCLE_OF_CUNNING = new CircleOfCunning();
    public static Spell SPELL_CLEANSE = new Cleanse();
    public static Spell SPELL_CORROSION = new Corrosion();
    public static Spell SPELL_CORRUPT = new Corrupt();
    public static Spell SPELL_COURIER = new Courier();
    public static Spell SPELL_CURE_LIGHT = new CureLight();
    public static Spell SPELL_CURE_MEDIUM = new CureMedium();
    public static Spell SPELL_CURE_SERIOUS = new CureSerious();
    public static Spell SPELL_DARK_MESSENGER = new DarkMessenger();
    public static Spell SPELL_DEMISE_ANIMAL = new DemiseAnimal();
    public static Spell SPELL_DEMISE_HUMAN = new DemiseHuman();
    public static Spell SPELL_DEMISE_LEGENDARY = new DemiseLegendary();
    public static Spell SPELL_DEMISE_MONSTER = new DemiseMonster();
    public static Spell SPELL_DIRT = new Dirt();
    public static Spell SPELL_DISINTEGRATE = new Disintegrate();
    public static Spell SPELL_DISPEL = new Dispel();
    public static Spell SPELL_DOMINATE = new Dominate();
    public static Spell SPELL_DRAIN_HEALTH = new DrainHealth();
    public static Spell SPELL_DRAIN_STAMINA = new DrainStamina();
    public static Spell SPELL_ESSENCE_DRAIN = new EssenceDrain();
    public static Spell SPELL_EXCEL = new Excel();
    public static Spell SPELL_FIREHEART = new FireHeart();
    public static Spell SPELL_FIRE_PILLAR = new FirePillar();
    public static Spell SPELL_FLAMING_AURA = new FlamingAura();
    public static Spell SPELL_FOCUSED_WILL = new FocusedWill();
    public static Spell SPELL_FOREST_GIANT_STRENGTH = new ForestGiant();
    public static Spell SPELL_FRANTIC_CHARGE = new FranticCharge();
    public static Spell SPELL_FROSTBRAND = new Frostbrand();
    public static Spell SPELL_FUNGUS_TRAP = new FungusTrap();
    public static Spell SPELL_GENESIS = new Genesis();
    public static Spell SPELL_GLACIAL = new Glacial();
    public static Spell SPELL_GOAT_SHAPE = new GoatShape();
    public static Spell SPELL_HEAL = new Heal();
    public static Spell SPELL_HELL_STRENGTH = new Hellstrength();
    public static Spell SPELL_HOLY_CROP = new HolyCrop();
    public static Spell SPELL_HUMID_DRIZZLE = new HumidDrizzle();
    public static Spell SPELL_HYPOTHERMIA = new Hypothermia();
    public static Spell SPELL_ICE_PILLAR = new IcePillar();
    public static Spell SPELL_INFERNO = new Inferno();
    public static Spell SPELL_LAND_OF_THE_DEAD = new LandOfTheDead();
    public static Spell SPELL_LIFE_TRANSFER = new LifeTransfer();
    public static Spell SPELL_LIGHT_OF_FO = new LightOfFo();
    public static Spell SPELL_LIGHT_TOKEN = new LightToken();
    public static Spell SPELL_LOCATE_ARTIFACT = new LocateArtifact();
    public static Spell SPELL_LOCATE_SOUL = new LocatePlayer();
    public static Spell SPELL_LURKER_IN_THE_DARK = new LurkerDark();
    public static Spell SPELL_LURKER_IN_THE_DEEP = new LurkerDeep();
    public static Spell SPELL_LURKER_IN_THE_WOODS = new LurkerWoods();
    public static Spell SPELL_MASS_STAMINA = new MassStamina();
    public static Spell SPELL_MEND = new Mend();
    public static Spell SPELL_MIND_STEALER = new MindStealer();
    public static Spell SPELL_MOLE_SENSES = new MoleSenses();
    public static Spell SPELL_MORNING_FOG = new MorningFog();
    public static Spell SPELL_NIMBLENESS = new Nimbleness();
    public static Spell SPELL_NOLOCATE = new Nolocate();
    public static Spell SPELL_OAKSHELL = new OakShell();
    public static Spell SPELL_OPULENCE = new Opulence();
    public static Spell SPELL_PAIN_RAIN = new PainRain();
    public static Spell SPELL_PHANTASMS = new Phantasms();
    public static Spell SPELL_PROTECT_ACID = new ProtectionAcid();
    public static Spell SPELL_PROTECT_FIRE = new ProtectionFire();
    public static Spell SPELL_PROTECT_FROST = new ProtectionFrost();
    public static Spell SPELL_PROTECT_POISON = new ProtectionPoison();
    public static Spell SPELL_PURGE = new Purge();
    public static Spell SPELL_REBIRTH = new Rebirth();
    public static Spell SPELL_REFRESH = new Refresh();
    public static Spell SPELL_REVEAL_CREATURES = new RevealCreatures();
    public static Spell SPELL_REVEAL_SETTLEMENTS = new RevealSettlements();
    public static Spell SPELL_RITE_OF_DEATH = new RiteDeath();
    public static Spell SPELL_RITE_OF_SPRING = new RiteSpring();
    public static Spell SPELL_RITUAL_OF_THE_SUN = new RitualSun();
    public static Spell SPELL_ROTTING_GUT = new RottingGut();
    public static Spell SPELL_ROTTING_TOUCH = new RottingTouch();
    public static Spell SPELL_SCORN_OF_LIBILA = new ScornOfLibila();
    public static Spell SPELL_SHARD_OF_ICE = new ShardOfIce();
    public static Spell SPELL_SIXTH_SENSE = new SixthSense();
    public static Spell SPELL_SMITE = new Smite();
    public static Spell SPELL_STRONGWALL = new StrongWall();
    public static Spell SPELL_SUMMON_SOUL = new SummonSoul();
    public static Spell SPELL_SUNDER = new Sunder();
    public static Spell SPELL_TANGLEWEAVE = new TangleWeave();
    public static Spell SPELL_TENTACLES = new DeepTentacles();
    public static Spell SPELL_TORNADO = new Tornado();
    public static Spell SPELL_TOXIN = new Toxin();
    public static Spell SPELL_TRUEHIT = new TrueHit();
    public static Spell SPELL_VENOM = new Venom();
    public static Spell SPELL_VESSEL = new Vessle();
    public static Spell SPELL_WARD = new Ward();
    public static Spell SPELL_WEAKNESS = new Weakness();
    public static Spell SPELL_WEB_ARMOUR = new WebArmour();
    public static Spell SPELL_WILD_GROWTH = new WildGrowth();
    public static Spell SPELL_WILLOWSPINE = new WillowSpine();
    public static Spell SPELL_WIND_OF_AGES = new WindOfAges();
    public static Spell SPELL_WISDOM_OF_VYNORA = new WisdomVynora();
    public static Spell SPELL_WORM_BRAINS = new WormBrains();
    public static Spell SPELL_WRATH_OF_MAGRANON = new WrathMagranon();
    public static Spell SPELL_ZOMBIE_INFESTATION = new ZombieInfestation();
    public static Spell SPELL_CONTINUUM = new Continuum();
    public static Spell SPELL_DISEASE = new Disease();
    public static Spell SPELL_FIREBALL = new Fireball();
    public static Spell SPELL_FORECAST = new Forecast();
    public static Spell SPELL_INCINERATE = new Incinerate();
    public static Spell SPELL_KARMA_BOLT = new KarmaBolt();
    public static Spell SPELL_KARMA_MISSILE = new KarmaMissile();
    public static Spell SPELL_KARMA_SLOW = new KarmaSlow();
    public static Spell SPELL_LIGHTNING = new Lightning();
    public static Spell SPELL_MIRRORED_SELF = new MirroredSelf();
    public static Spell SPELL_RUST_MONSTER = new RustMonster();
    public static Spell SPELL_SPROUT_TREES = new SproutTrees();
    public static Spell SPELL_STONESKIN = new StoneSkin();
    public static Spell SPELL_SUMMON = new Summon();
    public static Spell SPELL_SUMMON_SKELETON = new SummonSkeleton();
    public static Spell SPELL_SUMMON_WORG = new SummonWorg();
    public static Spell SPELL_SUMMON_WRAITH = new SummonWraith();
    public static Spell SPELL_TRUESTRIKE = new Truestrike();
    public static Spell SPELL_WALL_OF_FIRE = new WallOfFire();
    public static Spell SPELL_WALL_OF_ICE = new WallOfIce();
    public static Spell SPELL_WALL_OF_STONE = new WallOfStone();

    public static void addSpell(Spell spell) {
        spells.put(spell.getNumber(), spell);
        if (spell.isTargetCreature()) {
            creatureSpells.put(spell.getNumber(), spell);
        }
        if (spell.isTargetAnyItem()) {
            itemSpells.put(spell.getNumber(), spell);
        }
        if (spell.isTargetWound()) {
            woundSpells.put(spell.getNumber(), spell);
        }
        if (spell.isTargetTile()) {
            tileSpells.put(spell.getNumber(), spell);
        }
        if (spell.getEnchantment() != 0) {
            enchantments.put(spell.getEnchantment(), spell);
        }
    }

    public static final Spell getSpell(int number) {
        return spells.get(number);
    }

    public static final Spell[] getAllSpells() {
        return spells.values().toArray(new Spell[spells.size()]);
    }

    public static final Spell getEnchantment(byte num) {
        return enchantments.get(num);
    }

    public static final Spell[] getSpellsTargettingItems() {
        HashSet<Spell> toReturn = new HashSet<Spell>();
        Iterator<Integer> it = itemSpells.keySet().iterator();
        while (it.hasNext()) {
            toReturn.add(itemSpells.get(it.next()));
        }
        return toReturn.toArray(new Spell[toReturn.size()]);
    }

    public static final Spell[] getSpellsEnchantingItems() {
        HashSet<Spell> toReturn = new HashSet<Spell>();
        Iterator<Integer> it = itemSpells.keySet().iterator();
        while (it.hasNext()) {
            Spell spell = itemSpells.get(it.next());
            if (spell.getEnchantment() <= 0) continue;
            toReturn.add(spell);
        }
        return toReturn.toArray(new Spell[toReturn.size()]);
    }

    static {
        Spells.addSpell(SPELL_AURA_SHARED_PAIN);
        Spells.addSpell(SPELL_BEARPAWS);
        Spells.addSpell(SPELL_BLAZE);
        Spells.addSpell(SPELL_BLESS);
        Spells.addSpell(SPELL_BLESSINGS_OF_THE_DARK);
        Spells.addSpell(SPELL_BLOODTHIRST);
        Spells.addSpell(SPELL_BREAK_ALTAR);
        Spells.addSpell(SPELL_CHARM_ANIMAL);
        Spells.addSpell(SPELL_CIRCLE_OF_CUNNING);
        Spells.addSpell(SPELL_CLEANSE);
        Spells.addSpell(SPELL_CORROSION);
        Spells.addSpell(SPELL_CORRUPT);
        Spells.addSpell(SPELL_COURIER);
        Spells.addSpell(SPELL_CURE_LIGHT);
        Spells.addSpell(SPELL_CURE_MEDIUM);
        Spells.addSpell(SPELL_CURE_SERIOUS);
        Spells.addSpell(SPELL_DARK_MESSENGER);
        Spells.addSpell(SPELL_DEMISE_ANIMAL);
        Spells.addSpell(SPELL_DEMISE_HUMAN);
        Spells.addSpell(SPELL_DEMISE_LEGENDARY);
        Spells.addSpell(SPELL_DEMISE_MONSTER);
        Spells.addSpell(SPELL_DIRT);
        Spells.addSpell(SPELL_DISINTEGRATE);
        Spells.addSpell(SPELL_DISPEL);
        Spells.addSpell(SPELL_DOMINATE);
        Spells.addSpell(SPELL_DRAIN_HEALTH);
        Spells.addSpell(SPELL_DRAIN_STAMINA);
        Spells.addSpell(SPELL_ESSENCE_DRAIN);
        Spells.addSpell(SPELL_EXCEL);
        Spells.addSpell(SPELL_FIREHEART);
        Spells.addSpell(SPELL_FIRE_PILLAR);
        Spells.addSpell(SPELL_FLAMING_AURA);
        Spells.addSpell(SPELL_FOCUSED_WILL);
        Spells.addSpell(SPELL_FOREST_GIANT_STRENGTH);
        Spells.addSpell(SPELL_FRANTIC_CHARGE);
        Spells.addSpell(SPELL_FROSTBRAND);
        Spells.addSpell(SPELL_FUNGUS_TRAP);
        Spells.addSpell(SPELL_GENESIS);
        Spells.addSpell(SPELL_GLACIAL);
        Spells.addSpell(SPELL_GOAT_SHAPE);
        Spells.addSpell(SPELL_HEAL);
        Spells.addSpell(SPELL_HELL_STRENGTH);
        Spells.addSpell(SPELL_HOLY_CROP);
        Spells.addSpell(SPELL_HUMID_DRIZZLE);
        Spells.addSpell(SPELL_HYPOTHERMIA);
        Spells.addSpell(SPELL_ICE_PILLAR);
        Spells.addSpell(SPELL_INFERNO);
        Spells.addSpell(SPELL_LAND_OF_THE_DEAD);
        Spells.addSpell(SPELL_LIFE_TRANSFER);
        Spells.addSpell(SPELL_LIGHT_OF_FO);
        Spells.addSpell(SPELL_LIGHT_TOKEN);
        Spells.addSpell(SPELL_LOCATE_ARTIFACT);
        Spells.addSpell(SPELL_LOCATE_SOUL);
        Spells.addSpell(SPELL_LURKER_IN_THE_DARK);
        Spells.addSpell(SPELL_LURKER_IN_THE_DEEP);
        Spells.addSpell(SPELL_LURKER_IN_THE_WOODS);
        Spells.addSpell(SPELL_MASS_STAMINA);
        Spells.addSpell(SPELL_MEND);
        Spells.addSpell(SPELL_MIND_STEALER);
        Spells.addSpell(SPELL_MOLE_SENSES);
        Spells.addSpell(SPELL_MORNING_FOG);
        Spells.addSpell(SPELL_NIMBLENESS);
        Spells.addSpell(SPELL_NOLOCATE);
        Spells.addSpell(SPELL_OAKSHELL);
        Spells.addSpell(SPELL_OPULENCE);
        Spells.addSpell(SPELL_PAIN_RAIN);
        Spells.addSpell(SPELL_PHANTASMS);
        Spells.addSpell(SPELL_PROTECT_ACID);
        Spells.addSpell(SPELL_PROTECT_FIRE);
        Spells.addSpell(SPELL_PROTECT_FROST);
        Spells.addSpell(SPELL_PROTECT_POISON);
        Spells.addSpell(SPELL_PURGE);
        Spells.addSpell(SPELL_REBIRTH);
        Spells.addSpell(SPELL_REFRESH);
        Spells.addSpell(SPELL_REVEAL_CREATURES);
        Spells.addSpell(SPELL_REVEAL_SETTLEMENTS);
        Spells.addSpell(SPELL_RITE_OF_DEATH);
        Spells.addSpell(SPELL_RITE_OF_SPRING);
        Spells.addSpell(SPELL_RITUAL_OF_THE_SUN);
        Spells.addSpell(SPELL_ROTTING_GUT);
        Spells.addSpell(SPELL_ROTTING_TOUCH);
        Spells.addSpell(SPELL_SCORN_OF_LIBILA);
        Spells.addSpell(SPELL_SHARD_OF_ICE);
        Spells.addSpell(SPELL_SIXTH_SENSE);
        Spells.addSpell(SPELL_SMITE);
        Spells.addSpell(SPELL_STRONGWALL);
        Spells.addSpell(SPELL_SUMMON_SOUL);
        Spells.addSpell(SPELL_SUNDER);
        Spells.addSpell(SPELL_TANGLEWEAVE);
        Spells.addSpell(SPELL_TENTACLES);
        Spells.addSpell(SPELL_TORNADO);
        Spells.addSpell(SPELL_TOXIN);
        Spells.addSpell(SPELL_TRUEHIT);
        Spells.addSpell(SPELL_VENOM);
        Spells.addSpell(SPELL_VESSEL);
        Spells.addSpell(SPELL_WARD);
        Spells.addSpell(SPELL_WEAKNESS);
        Spells.addSpell(SPELL_WEB_ARMOUR);
        Spells.addSpell(SPELL_WILD_GROWTH);
        Spells.addSpell(SPELL_WILLOWSPINE);
        Spells.addSpell(SPELL_WIND_OF_AGES);
        Spells.addSpell(SPELL_WISDOM_OF_VYNORA);
        Spells.addSpell(SPELL_WORM_BRAINS);
        Spells.addSpell(SPELL_WRATH_OF_MAGRANON);
        Spells.addSpell(SPELL_ZOMBIE_INFESTATION);
        Spells.addSpell(SPELL_CONTINUUM);
        Spells.addSpell(SPELL_DISEASE);
        Spells.addSpell(SPELL_FIREBALL);
        Spells.addSpell(SPELL_FORECAST);
        Spells.addSpell(SPELL_INCINERATE);
        Spells.addSpell(SPELL_KARMA_BOLT);
        Spells.addSpell(SPELL_KARMA_MISSILE);
        Spells.addSpell(SPELL_KARMA_SLOW);
        Spells.addSpell(SPELL_LIGHTNING);
        Spells.addSpell(SPELL_MIRRORED_SELF);
        Spells.addSpell(SPELL_RUST_MONSTER);
        Spells.addSpell(SPELL_SPROUT_TREES);
        Spells.addSpell(SPELL_STONESKIN);
        Spells.addSpell(SPELL_SUMMON);
        Spells.addSpell(SPELL_SUMMON_SKELETON);
        Spells.addSpell(SPELL_SUMMON_WORG);
        Spells.addSpell(SPELL_SUMMON_WRAITH);
        Spells.addSpell(SPELL_TRUESTRIKE);
        Spells.addSpell(SPELL_WALL_OF_FIRE);
        Spells.addSpell(SPELL_WALL_OF_ICE);
        Spells.addSpell(SPELL_WALL_OF_STONE);
    }
}

