package com.wurmonline.shared.constants;

public interface CounterTypes {
   byte COUNTER_TYPE_PLAYERS = 0;
   byte COUNTER_TYPE_CREATURES = 1;
   byte COUNTER_TYPE_ITEMS = 2;
   byte COUNTER_TYPE_TILES = 3;
   byte COUNTER_TYPE_STRUCTURES = 4;
   byte COUNTER_TYPE_WALLS = 5;
   byte COUNTER_TYPE_TEMPITEMS = 6;
   byte COUNTER_TYPE_FENCES = 7;
   byte COUNTER_TYPE_WOUNDS = 8;
   byte COUNTER_TYPE_CREATURESKILL = 9;
   byte COUNTER_TYPE_PLAYERSKILL = 10;
   byte COUNTER_TYPE_TEMPLATESKILL = 11;
   byte COUNTER_TYPE_TILEBORDER = 12;
   byte COUNTER_TYPE_BANKS = 13;
   byte COUNTER_TYPE_PLANETS = 14;
   byte COUNTER_TYPE_SPELLS = 15;
   byte COUNTER_TYPE_PLANS = 16;
   byte COUNTER_TYPE_CAVETILES = 17;
   byte COUNTER_TYPE_SKILLIDS = 18;
   byte COUNTER_TYPE_BODYIDS = 19;
   byte COUNTER_TYPE_COINIDS = 20;
   byte COUNTER_TYPE_WCCOMMANDS = 21;
   byte COUNTER_TYPE_MISSIONPERFORMED = 22;
   byte COUNTER_TYPE_FLOORS = 23;
   byte COUNTER_TYPE_ILLUSIONS = 24;
   byte COUNTER_TYPE_TICKETS = 25;
   byte COUNTER_TYPE_POIIDS = 26;
   byte COUNTER_TYPE_TILECORNER = 27;
   byte COUNTER_TYPE_BRIDGE_PARTS = 28;
   byte COUNTER_TYPE_REDEEM_IDS = 29;
   byte COUNTER_TYPE_MENU_REQUEST = 30;
   byte COUNTER_TYPE_TEMPSKILLS = 31;
   byte COUNTER_TYPE_TEMPWOUNDS = 32;
}
