package com.wurmonline.shared.constants;

public interface EffectConstants {
   short EFFECT_CAMPFIRE = 0;
   short EFFECT_LIGHTNING_BOLT = 1;
   short EFFECT_ALTAR_LIGHT_BEAM_HOLY = 2;
   short EFFECT_ALTAR_LIGHT_BEAM_UNHOLY = 3;
   short EFFECT_XMAS_LIGHTS = 4;
   short EFFECT_FIREWORKS_ONE = 5;
   short EFFECT_FIREWORKS_TWO = 6;
   short EFFECT_FIREWORKS_THREE = 7;
   short EFFECT_FIREWORKS_FOUR = 8;
   short EFFECT_FIREWORKS_FIVE = 9;
   short EFFECT_METEOR = 10;
   short EFFECT_PLATEAU = 11;
   short EFFECT_ERUPTION = 12;
   short EFFECT_INDENTATION = 13;
   short EFFECT_RAVINE = 14;
   short EFFECT_ISLAND = 15;
   short EFFECT_GLOBAL_DARKNESS = 16;
   short EFFECT_GLOBAL_BRIGHTNESS = 17;
   short EFFECT_GLOBAL_DOOM = 18;
   short EFFECT_GLOBAL_ITEMSPAWN = 19;
   short CHALLENGE_STEPONE = 20;
   short CHALLENGE_STEPTWO = 21;
   short CHALLENGE_STEPTHREE = 22;
   short CHALLENGE_STEPFOUR = 23;
   short CHALLENGE_CAPTURE_TOWER = 24;
   short RIFT_SPAWN = 25;
   short EFFECT_PROJECTILELANDING = 26;
   short EFFECT_GENERIC = 27;
}
